#!/usr/bin/python3
from sys import argv
import math
""" factorize large number to a product of 2 small numbers"""


def factorial(num):
    """gets factors of num
    Args: num (int): number"""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, int(num//i), i))
    else:
        sq_rt = int(math.sqrt(num)) + 1
        for i in range(3, sq_rt, 2):
            if num % i == 0:
                print("{}={}*{}".format(num, int(num//i), i))
                return
            if num % (sq_rt + i) == 0:
                print("{}={}*{}".format(num, sq_rt + i, int(num//(sq_rt + i))))
                return
            if num % (sq_rt - i) == 0:
                print("{}={}*{}".format(num, sq_rt - i, int(num//(sq_rt - i))))
                return


def factors(fname):
    """ opens, reads and prints factors in file"""

    with open(fname) as f:
        for i in f.readlines():
            nm = int(i)
            result = factorial(nm)


if __name__ == "__main__":
    factors(argv[1])
