#!/usr/bin/python3
from sys import argv
import math
""" factorize large number to a product of 2 small numbers"""


def is_prime_num(num):
    """ checks if prime number"""
    i = 3
    if num % 2 == 0:
        return False
    while i * i <= num:
        if num % i == 0:
            return False
        i += 2
    return True


def factorial(num):
    """gets factors of num
    Args: num (int): number"""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, int(num//i), i))
    else:
        sq_root = math.sqrt(num)
        if sq_root % 1 == 0:
            print("{}={}*{}".format(num, sq_root, int(num/sq_root)))
            return
        sq_root = int(sq_root) + 1
        for i in range(3, sq_root, 2):
            if num % i == 0:
                if is_prime_num(i):
                    print("{}={}*{}".format(num, int(num/i), i))
                    return


def factors(fname):
    """ opens, reads and prints factors in file"""

    with open(fname) as f:
        for i in f.readlines():
            nm = int(i)
            result = factorial(nm)


if __name__ == "__main__":
    factors(argv[1])
